# Generated by Django 5.2 on 2025-05-13 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eighth_day', '0002_user1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
