# Generated by Django 5.2 on 2025-05-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eighth_day', '0003_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user1',
        ),
    ]
