# Generated by Django 5.2 on 2025-05-12 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fifth_day', '0002_product_food_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_name', models.CharField(max_length=50, null=True)),
                ('Customer_since', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_number', models.CharField(max_length=50, null=True)),
                ('Order_data', models.DateField(null=True)),
                ('Quantity', models.FloatField(default=0)),
                ('Amount', models.FloatField(default=0)),
                ('Customer_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seventh_day.customer')),
                ('Product_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fifth_day.product')),
            ],
        ),
    ]
