# Generated by Django 5.2 on 2025-05-09 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifth_day', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Food_Product',
            field=models.BooleanField(default=False),
        ),
    ]
