# Generated by Django 5.2 on 2025-05-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_id', models.IntegerField(default=0)),
                ('Student_Name', models.CharField(max_length=50, null=True)),
                ('Student_Course', models.CharField(max_length=50, null=True)),
                ('Student_Deprt', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
